services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/hummingbird
    environment:
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_USER=test_user
      - POSTGRES_DB=test_db
volumes:
  db:
    driver: local
