name: Swift nightly build

on:
  schedule:
    - cron: '0 1 * * 1'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['bionic', 'focal', 'amazonlinux2']
    container:
      image: swiftlang/swift:nightly-5.7-${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies (Ubuntu)
      if: ${{ matrix.image == 'bionic' || matrix.image == 'focal'}}
      run: |
        apt-get update -qq
        apt-get install -q -y libsqlite3-dev
    - name: Install dependencies (Amazon Linux2/CentOS8)
      if: ${{ matrix.image == 'amazonlinux2' || matrix.image == 'centos7'}}
      run: |
        yum -y update
        yum -y install sqlite-devel
    - name: Build Examples
      run: |
        ./scripts/build-all.sh
